Pile overlay revamp
ArnoldSmith86/virtualtabletop pull request #1019
Opened 2021-12-13 03:34 UTC by mousewax

Against my better judgement I am still doing stuff. This is to partially address a very old Issue.
https://github.com/ArnoldSmith86/virtualtabletop/issues/53

It's not fully polished but it works with no errors from the back-en.

The split section has three inputs. You can change either side of the split or use the slider to change the split. 
![image](https://user-images.githubusercontent.com/12822213/145748246-6fb3d267-bbff-4434-a224-ff6433be4408.png)

Still to do: When a user enters a number in either pile input that is out of bounds, change it to be in bounds.

2021-12-13 03:35 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:4019/pr-test (or any other room on that server)

2021-12-13 03:45 UTC, 96LawDawg commented
Good start.  Everything works like it should.  As you say, just needs some polish.  I don't suppose it is possible to have the numbers on the split pile change while you drag the slider?  Right now you can increment the numbers using scroll bars.  Or you can drag the slider.  But the slider doesn't change the numbers until you let go.

2021-12-13 03:50 UTC, mousewax commented
The numbers are updated from a `change` event on the slider. The event does not fire until the user lets go. It's the same deal when you hold down the up or down icons on the number inputs.

Though some UI libraries seem to have ways to get around that. I will do some research.

2021-12-13 04:02 UTC, mousewax commented
Ta-dah!

2021-12-13 04:07 UTC, 96LawDawg commented
Fantastic!  And fast.  But can you do the same thing with the scrollbar?  In other words "The little lights are not twinkling, Clark."  (Movie playing in the background in the other room now.  Hopefully you get the reference).

2021-12-13 04:12 UTC, bjalder26 commented
I think TestCafe will need to be updated to account for the modal.

2021-12-13 04:28 UTC, 96LawDawg commented
Two more thoughts.  Should the slider and scrollbar start at 1 and go to n-1?  There is no point in splitting a pile of 0 or a pile of all the cards.  Sure, you can do that on production now, but should we allow that?

Also, you can enter a decimal number.  It rounds up.  That happens on production as well.  Maybe prevent decimals?

2021-12-13 04:46 UTC, 96LawDawg commented
Perhaps an unintended side effect ... You can't backspace to clear out the current entry and just type something new in.  It starts at 26.  Backspace and it clears the 2.  Backspace again and it reduces to 1.  Then you have to type 15 then delete just the 1 to get 5.

Also, you can still type 52 and get a 52 card split.

Also, I'm just really nitpicking now trying to find out it can be broken.  I have never ONCE ever used split in an actual game.  So none of this really matters to me.

2021-12-13 04:48 UTC, 96LawDawg commented
Another thought.  Could the overlay just be a pop up like pictured in #53 or in the Custom Pile Memo demo at https://virtualtabletop.io/DemoLibrary?  It would be nice if the overlay was very close to where the pile handle was to start with.

2021-12-13 04:55 UTC, mousewax commented
> Another thought. Could the overlay just be a pop up like pictured in #53 or in the Custom Pile Menu demo at https://virtualtabletop.io/DemoLibrary? It would be nice if the overlay was very close to where the pile handle was to start with.

*I* cannot do that, but I am positive it can be done by someone with more knowledge than me. 

> You can't backspace to clear out the current entry and just type something new in. It starts at 26. Backspace and it clears the 6. Backspace again and it reduces to 1. Then you have to type 15 then delete just the 1 to get 5.

I cannot change that. Double click/tap the number to highlight it then type a number? It's a mild annoyance but that kind of thing is a normal computer interaction.

2022-02-02 17:18 UTC, ArnoldSmith86 requested changes
I didn't look at the CSS. The code looks fine for the most part (see comments).

2022-02-02 17:18 UTC, ArnoldSmith86 commented on client/js/widgets/pile.js
> +
What's the plan here? You marked it as "ready to review" but this doesn't look finished yet. Not that that's a problem; I just don't know how to review this. :smile:

2022-02-02 17:18 UTC, ArnoldSmith86 commented on client/js/widgets/pile.js
> +      $('#pileOverlay > .modal').appendChild(or1label);
I don't see an `-OR-` on the overlay. Is this a WIP?

2022-02-02 17:18 UTC, ArnoldSmith86 commented on client/js/widgets/pile.js
> +      $('#pileOverlay > .modal').appendChild(splitLabel);
Same question for the `-OR-`.

2022-02-02 17:18 UTC, ArnoldSmith86 commented on client/js/widgets/pile.js
> +      splitInput.setAttribute("aria-valuemax", childCount);
Are the `aria` values supposed to be different?

2022-02-02 17:18 UTC, ArnoldSmith86 commented on client/js/widgets/pile.js
> +      splitInputSlider.setAttribute("aria-valuemax", childCount);
Same question about `aria`.

2022-02-02 17:18 UTC, ArnoldSmith86 commented on client/js/widgets/pile.js
> +      denominatorInput.setAttribute("aria-valuemax", childCount);
Same question. Does `aria` support even make sense? I'm pretty sure that games will never be playable using a screen reader. But I don't know if it's useful for any other circumstances.

2022-10-14 20:06 UTC, RaphaelAlvez commented
this looks so much better @mousewax do you mind just taking a look at what was commented?

also, any reason why the overlay is offset?

2023-04-14 10:36 UTC, ArnoldSmith86 approved these changes
I addressed my own comments.

Somebody else should probably review this as well. :smile:

2023-04-14 10:37 UTC, ArnoldSmith86 commented
![image](https://user-images.githubusercontent.com/73538315/232022017-d89dd391-0cb0-4be9-a813-65ad655ced97.png)

This is what it looks like for me on Firefox/Linux now. Please post screenshots if it looks different for you on any platform.

2023-04-14 13:39 UTC, 96LawDawg approved these changes
Approved through test.  Looks the same to me on all browsers, including Safari mobile.  The only thing I noticed is that if the card count gets really high, like in CAH, then the slider isn't centered when the window opens.  It works fine in Flight with 200 cards, but not in CAH with 500.

![CAH](https://user-images.githubusercontent.com/76912527/232059341-bd6189d1-6ce5-4bde-a1d0-c4be845690bc.jpg)

2023-04-14 15:43 UTC, merged