fix crashes with invalid values for `svgReplaces` and `faces`
ArnoldSmith86/virtualtabletop pull request #1165
Opened 2022-03-24 21:03 UTC by ArnoldSmith86

It is not easy to make `svgReplaces` evaluate to `null` but it is possible with `inheritFrom`. This causes a crash which this PR fixes.

Similar behavior happens for `faces` where the code assumed it is an array. The resulting crash should now also be fixed.

Additionally this PR fixes a crash when indexing a variable that evaluates to `null` in a dynamic expression.

2022-03-24 21:03 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1165/pr-test (or any other room on that server)

2022-03-24 21:38 UTC, rogerl50 commented
This appears to fix the problem that resulted in this PR.

2022-03-24 21:40 UTC, rogerl50 approved these changes
Approved through test of the original test case (only).

2022-03-25 15:43 UTC, robartsd requested changes

2022-03-25 15:49 UTC, ArnoldSmith86 commented on client/js/widgets/basicwidget.js
> +    const d = this.faces()[this.get('activeFace')][property];
But the new `this.faces` should always return an array. That's what it's for. And the `if` two lines prior checks if `activeFace` is a valid index of `faces`.

2022-03-25 15:55 UTC, robartsd approved these changes

2022-03-25 15:59 UTC, ArnoldSmith86 commented on client/js/widgets/basicwidget.js
> +    const d = this.faces()[this.get('activeFace')][property];
Yeah, good catch. I just did a search and replace for `this.get('faces')`.

2022-05-16 20:12 UTC, merged