added css property to faceTemplate
ArnoldSmith86/virtualtabletop pull request #121
Opened 2021-01-16 16:13 UTC by robartsd

Adds ability to add css property to faceTemplate and elements of faceTemplate.objects. Also adds rotation property to elements of faceTemplate.objects.

2021-01-16 16:13 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3121/pr-test (or any other room on that server)

2021-01-16 16:21 UTC, ArnoldSmith86 requested changes

2021-01-16 16:21 UTC, ArnoldSmith86 commented on client/js/widgets/card.js
> +          css += '; transform: rotate(${object.rotation}deg)';
For `${object.rotation}` to work you need to use backticks instead of quotes.

2021-01-16 16:21 UTC, ArnoldSmith86 commented on client/js/widgets/card.js
> +      if (face.css !== undefined) {
Most of the code omits braces for one line and has no space after `if`s. It's not important though.

2021-01-16 16:24 UTC, ArnoldSmith86 commented
And don't forget to add the changes here: https://github.com/ArnoldSmith86/virtualtabletop/wiki/Upcoming-Changes

2021-01-16 16:54 UTC, ArnoldSmith86 requested changes

2021-01-16 16:54 UTC, ArnoldSmith86 commented on client/js/widgets/card.js
> +        ccs += object.rotation ? `; transform: rotate(${object.rotation}deg)` : '';
`ccs` ;)

2021-01-16 17:07 UTC, robartsd commented on client/js/widgets/card.js
> +        ccs += object.rotation ? `; transform: rotate(${object.rotation}deg)` : '';
Thanks for your help.

2021-01-16 23:52 UTC, robartsd commented
OK, I think it is ready now. ArnoldSmith86, thanks for your patience with me as I learn github. I modified a deck to make extra large indexes by using css to crop the pip area from the standard cards and set the color of the card text (workaround for not having dynamic text color: the card itself adds a css variable which gets inherited by the face objects to apply to the text color).

2021-01-17 13:50 UTC, ArnoldSmith86 approved these changes
Looks nice.

I had the same idea with the variables. Good to know you already tested it. :D

2021-01-19 15:23 UTC, robartsd commented
> Looks nice.
> 
> I had the same idea with the variables. Good to know you already tested it. :D

I'm thinking about making a patch that would enable all faceTemplate.objects properties to be dynamic. Would depreciate "valueType":"dynamic" replacing with "dynamicProperties":{"_objectProperty_":"_cardProperty_"}. I need to brush up on JS objects before I write the code.

2021-01-24 14:32 UTC, RaphaelAlvez commented
Did you add face sizes? I'll make tests to this later today. If you have a test room in you machine please upload it to the server

2021-01-24 21:48 UTC, robartsd commented
> Did you add face sizes? I'll make tests to this later today. If you have a test room in you machine please upload it to the server

No, I did not do anything with #134 in this pull request and do not intend to. I was simply mentioning this in #134 to comment that a resizing property on the faceTemplate should not  have repeat values. Repeat values would be appropriate for faceTemplate objects and would be enabled via the css property added by this pull request. I might add a demo of a repeating background card back on this pull request test server later.

2021-01-28 03:29 UTC, RaphaelAlvez approved these changes
Tested and approved. Sorry for the delay I tested it a couple of days ago but forgot to approve

2021-01-28 03:29 UTC, merged