add new jokers and new card back; add license info
ArnoldSmith86/virtualtabletop pull request #1560
Opened 2023-01-23 08:12 UTC by tsankuanglee

## Joker cards

Adding two new joker images as alternatives to the existing two. The main motivation is to provide better visibility when the cards are stacked with a small offset.

New:
![image](https://user-images.githubusercontent.com/1425438/213991215-42eb0106-549b-42e2-b07b-6e9a5a485e84.png)
Original:
![image](https://user-images.githubusercontent.com/1425438/213991307-9c2def0f-3d23-4c19-ae31-12d354b69ab2.png)

These new cards also try to provide a closer art style to the rest of the cards (while keeping the artistic convention that joker cards are supposed to be, well, jokes).

## New card back

The new card back provides a more obvious "card look".

2023-01-23 08:13 UTC, tsankuanglee commented
Reviewers, please help double check the license validity. Thanks!

2023-01-23 08:13 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1560/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1560-pr-test`.

2023-01-23 22:54 UTC, 96LawDawg approved these changes
Seems like a good idea to me.  The license looks good.  It is slightly different in execution.  Other licenses are in room.html (for our default stuff) or in the JSON attribution property.  But this works as far as I'm concerned.

2023-01-25 02:16 UTC, RaphaelAlvez requested changes
This should be added to the decks in add widget overlay otherwise, people will not use them. They are indeed an improvement. 

What you need to change is around line 475 of editmode.js

2023-01-29 23:45 UTC, tsankuanglee commented
> This should be added to the decks in add widget overlay otherwise, people will not use them. They are indeed an improvement.
> 
> What you need to change is around line 475 of editmode.js

Good point. Thanks for the pointer. Done.

2023-01-30 00:44 UTC, tsankuanglee commented
working on TestCafe

2023-01-30 05:19 UTC, tsankuanglee commented on assets/cards-default/3B.svg
> +<svg width="57.145mm" height="88.899mm" version="1.1" viewBox="0 0 57.145 88.899" xmlns="http://www.w3.org/2000/svg"><g transform="translate(-15.798 -11.113)"><path d="m72.855 97.411c0 1.3817-1.0548
Per our conversation on Discord, we'll use this one for now and replace it when we have a better version in the future.

2023-01-31 05:38 UTC, tsankuanglee commented
This PR is ready to go @RaphaelAlvez .

Per our conversation in Discord, we'll leave the card back image as is. Not sure how to resolve requested change here -- the latest commit includes the Deck Editor changes already.

2023-02-01 07:47 UTC, ArnoldSmith86 commented
Was there a discussion on Discord about _replacing_ 1J and 2J? I would have thought that we would add the new ones as 3J and 4J.

2023-02-01 11:21 UTC, merged

2023-02-01 13:48 UTC, 96LawDawg commented
> Was there a discussion on Discord about _replacing_ 1J and 2J? I would have thought that we would add the new ones as 3J and 4J.

Yes.  3-4 people said replace.  Here:  https://discord.com/channels/770758631146782780/770758631146782783/1069402520679632986.