added `icon` support to buttons, basic widgets, dice and cards
ArnoldSmith86/virtualtabletop pull request #1937
Opened 2023-11-12 14:04 UTC by ArnoldSmith86

This PR is meant to make using the awesome included icon collections easy. For now in the JSON editor, in the next step with proper UI.

**Without this PR**, you had to know this voodoo for material icons (and it doesn't even scale with the size):

```JSON
  "classes": "material-icons",
  "css": {
    "font-size": "68px"
  },
  "text": "restart_alt"
```

And this voodoo for game-icons:

```JSON
  "color": "white",
  "css": {
    "background-size": "70%"
  },
  "image": "/i/game-icons.net/delapouite/control-tower.svg",
  "svgReplaces": {
    "#000": "color"
  }
```

And even different voodoo for emojis or the VTT symbols font.

Now it becomes this:

![image](https://github.com/user-attachments/assets/498d66ff-8be6-4ba0-8940-628436254387)

Want text and icon?

![image](https://github.com/user-attachments/assets/fefe3ca3-b9db-49a4-aaef-d4b958c78df6)

Automatically uses the same color property as the text:

![image](https://github.com/user-attachments/assets/a278d124-0dd1-4c4f-869b-565ed51196c3)

And even the same hover color:

![image](https://github.com/user-attachments/assets/1593c2ee-673a-4375-9b5c-bbef21b669b9)

If you want something more fancy, you can switch to the advanced options:

![image](https://github.com/user-attachments/assets/06fe9827-da3c-4e39-a9ef-82d44d461719)

Or combine multiple icons and customize them:

![image](https://github.com/user-attachments/assets/aefceed2-4e79-4f05-b2ab-d118fdaad043)

Or go crazy and even customize the separate shapes of game-icons:

![image](https://github.com/user-attachments/assets/27537173-39e5-4f65-8908-a5910dd29055)

---

Additionally `svgReplaces` now supports this syntax for replacing different occurrences with different values:

```JSON
{
  "svgReplaces": {
    "#000": [ "red", "white" ]
  },
  "red": "red",
  "white": "white"
}
```

---

- [x] `[card_H]` (and others) show `[card]` instead. Might be unrelated.
- [x] Support `textColorOH`.
- [x] Add to dice.
- [x] Add outline support.
- [x] Fix missing things for deck generation.
- [x] Align and auto-size text next to icons.
- [x] Fix color on basic widgets.
- [x] Enable coloring different areas in game-icons.net svgs?
- [x] Check why images are too big on my phone.
- [x] Allow asset URLs as icons.
- [x] Make hoverColor work on all widget types?
- [x] Make `offsetX` and `offsetY` relative?
- [x] Resolve margin vs scale.
- [x] Changing `svgReplaces` no longer updates the widget.
- [x] Allow `${PROPERTY x}` syntax in `icon`.
- [x] Having `color: ["red","blue"], hoverColor: ""` makes everything black on hover instead of not changing anything.
- [x] JSON commands don't seem to work inside dice faces.
- [x] Different stroke properties for different areas?
- [x] Multiple icons (and text) in a card face object? (for reusing icon definitions from other widgets)
- [x] Rotation in cards is applied twice now.
- [x] JSON editor commands for cards?
- [x] `strokeWidth` is relative on images (to 512px) and absolute on fonts.
- [x] Test integer and bool JSON editor commands on arrays.
- [x] Can't have normal strokeWidth but no hoverStrokeWidth because 0 gets overridden.
- [x] ~~Gradients?~~ It's not _that_ difficult but we can add it later.
- [x] ~~Shadows?~~ It's not _that_ difficult but we can add it later.
- [x] ~~Add `textColor`.~~ Doesn't make sense as a property of an icon.
- [ ] Give text property advanced options like icon? Nice to have, but not essential
- [ ] Make multi-line text work better when combined with icon
- [ ] Different emoji sizes in the symbol picker between Firefox and Chrome
- [ ] A monochrome and a color emoji in the same button don't align nicely
- [ ] Test and fix advanced options with monochrome emojis

This line will be added to the wiki for basic widget and button, and a similar entry with appropriate tweaks will be made for cards and decks.

```

| icon     |   null    |  Adds an icon or emoji from a curated list (or custom image uploaded by the user) to the widget. The value can be just text that is automatically inserted by the JSON Editor. Or using advanced settings, the icon can be an object with the following key value pairs (with the default value following in parenthesis): name (the name of the icon), scale (1), offsetX (0), offsetY (0), rotation (0), color (""), strokeColor (""), strokeWidth (0), hoverColor (""), hoverStrokeColor (""), hoverStrokeWidth (null)  | [Icons & Emojis](https://virtualtabletop.io/tutorial/icons) |

```

2023-11-12 14:06 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: https://test.virtualtabletop.io/PR-1937/pr-test (or any other room on that server)

After merging, a backup will be available at `https://beta.virtualtabletop.io/editor/PR1937-pr-test`.

2023-11-12 14:13 UTC, ArnoldSmith86 commented
**Edit: test server is working now.**

GitHub seems to have problems at the moment which seems to cause the PR test server to use an old commit. The PR test room is supposed to look like this:

![image](https://github.com/ArnoldSmith86/virtualtabletop/assets/73538315/52830211-25ab-481d-a15c-bfd42b3ec187)

The four types of icons currently in the VTT repo are shown: Material Icons, internal VTT symbols font, Noto Emoji and game-icons.net.

2023-11-12 16:28 UTC, 96LawDawg commented
This is great.  I'll have to explore the new default for textColor some.  And still glitchy in displaying the emoji like in the other PR.  But otherwise, this is awesome.

2023-11-12 17:13 UTC, 96LawDawg commented
For the textColor thing, there is a possibility of breaking things.  The Button Appearance tutorial, Introduction variant has this on production:

![Production](https://github.com/ArnoldSmith86/virtualtabletop/assets/76912527/ea6e04dc-f483-4e8c-ac44-ffb6ac4bab60)

And this in this PR:

![This PR](https://github.com/ArnoldSmith86/virtualtabletop/assets/76912527/c5a802bf-9498-4aa5-bfbc-3d62c277ca69)

But if you need it for this PR, I say we go with our new more relaxed approach to breaking things: as long as it doesn't break too many things too badly, do it!

2023-11-12 17:16 UTC, ArnoldSmith86 commented
It's not necessary to break that. I'll look into it.

2023-11-13 20:49 UTC, ArnoldSmith86 commented
How about now?

2023-11-13 22:23 UTC, 96LawDawg commented
Works in Chromium and Firefox on Windows 11.  Does not work on iOS on newish iPad.

2024-02-05 10:52 UTC, ArnoldSmith86 commented
I copied my local test room to https://test.virtualtabletop.io/PR-1937/ick2 but it's a bit messy.. :grin:

2024-02-08 16:36 UTC, 96LawDawg commented
> One more important aspect of this is that `svgReplaces` is a bit too inflexible for setting different parts of a game-icons.net icon to different colors.
> 

Would changing the syntax here for `svgReplaces` conflict with or make it harder to implement #1900?  Just something to keep in mind.  I think that the additional flexibility you suggest is great, but just want to make sure we are thinking that through.

2024-02-08 16:39 UTC, ArnoldSmith86 commented
> Would changing the syntax here for `svgReplaces` conflict with or make it harder to implement #1900?

It shouldn't. But since I suggested that, I looked at an example SVG and they don't actually have `#000` in there multiple times. It's just one `<path>` with `M`s in there to split it. I still want to try to make it happen for this new icon stuff though.

2024-02-08 16:45 UTC, 96LawDawg commented
True for the icons from the game-icons.net site.  But obviously there are other SVGs that exist that do have multiple colors and being able to replace multiple svg colors would be a nice addition somewhere, somewhen.

2024-09-02 21:19 UTC, ArnoldSmith86 commented
I'm done with my todo list and marked this "ready for review". I'm sure we'll find some stuff to fix.

I copied my local tests from development to these test server rooms:

https://test.virtualtabletop.io/PR-1937/tests1
https://test.virtualtabletop.io/PR-1937/tests2
https://test.virtualtabletop.io/PR-1937/tests3
https://test.virtualtabletop.io/PR-1937/tests4
https://test.virtualtabletop.io/PR-1937/tests5
https://test.virtualtabletop.io/PR-1937/tests6

Maybe something can be used for a tutorial or whatever.

2024-09-13 17:48 UTC, 96LawDawg commented
How do you change the font size when the text covers more than one line?  css font-size did not work

```JSON
 "css": {
    "font-size": "40px"
  },
  "icon": {
    "name": "delapouite/brute",
    "scale": 0.8
  },
  "text": "Brute\nIcon",
  ```

2024-09-13 17:50 UTC, ArnoldSmith86 commented
It's not meant to be changed. Does the layout break?

2024-09-13 17:52 UTC, 96LawDawg commented
Depends what you mean by "break."  It becomes unreadable.
![Screenshot 2024-09-13 125201](https://github.com/user-attachments/assets/44ef99d7-12c2-49ab-9fc6-6bb84c25e4c6)

2024-09-13 18:07 UTC, ArnoldSmith86 commented
Maybe we can tweak the layout a bit so it works better out of the box.

You can of course reach it with `css`. You can look at the HTML structure and class names in imagewidget.css or the dev tools.

2024-09-13 18:16 UTC, 96LawDawg commented
> Maybe we can tweak the layout a bit so it works better out of the box.

I think it makes sense to at least try.  If I have 2 icons, I can adjust one to be bigger or smaller by using scale, or move it using the advanced options like offsetX and Y.

> You can of course reach it with `css`. 

Not easily.  It seems that the css property is completely overridden.  For example, in addition to not changing the font-size, changing color that way also has no effect.  Maybe we just need to add the same advanced options for the text property?  Instead of scale, support font-size.  Allow for offset on the text, allow for color change on the text?

2024-09-13 18:23 UTC, ArnoldSmith86 commented
Color uses the widget text color:

![image](https://github.com/user-attachments/assets/cae427b2-57a6-4cb7-b607-9e39b5667c9d)

2024-09-13 18:38 UTC, ArnoldSmith86 commented
It's not like I don't agree. But I think it's good that icon+text uses the `text` property of the widget:

```JSON
{
  "type": "button",
  "id": "button",
  "text": "Text",
  "icon": "sync"
}
```

Feels right that you then have text or icon or both or none.

But like that the text is outside of `icon` and it would be weird to have properties about it inside `icon` (would have to be restructured).

But: it's also weird that now the text auto-scales when you have text+icon but it doesn't auto-scale when you just have text.

---

Oh, I reread your comment and you're suggesting something like this, right:

```JSON
{
  "type": "button",
  "id": "button",
  "text": {
    "value": "Text",
    "scale": 2
  },
  "icon": "sync"
}
```

---

For your example with the tiny text, it's obvious though that the algorithm for the alignment can be improved to make it bigger automatically. I think it just needs to give the text more height instead of 50%.

2024-09-13 18:43 UTC, 96LawDawg commented
> Oh, I reread your comment and you're suggesting something like this, right:

Yes.  For consistency, it would be good if we didn't have things like textColor as a stand-alone property (of course, we have to leave it for compatibility), but make the text property have advanced options like icon.

```JSON
{
  "type": "button",
  "id": "button",
  "text": {
    "value": "Text",
    "scale": 2,
    "color":"blue",
    "hoverColor": "red",
    "offsetX": -10  
  },
  "icon": "sync"
}
```

2024-09-22 18:19 UTC, ArnoldSmith86 commented
It's not like I don't like your suggestion about customizing `text` but I gotta say that thinking about it demotivates me a lot. :grinning:

I made it now reserve 2/3rds of the height if the text includes a newline. If it doesn't, it's the same as before. No idea if that helps...

2024-09-22 23:16 UTC, 96LawDawg commented
> It's not like I don't like your suggestion about customizing `text` but I gotta say that thinking about it demotivates me a lot. 

Then don't do it.  This is probably good enough.  I was holding off on reviewing until you figured out what you wanted to do.  I'll try to review it as is this week and also work up a tutorial.

> I made it now reserve 2/3rds of the height if the text includes a newline. If it doesn't, it's the same as before. No idea if that helps...

It does help.  It isn't perfect.  And it doesn't work the same way as text without icons.  But this is probably good enough.

2024-10-20 20:49 UTC, 96LawDawg approved these changes
Approved through test.  I added a tutorial for Icons & Emojis.  I updated the Dice tutorial.  I updated the Button Appearance to tutorial (and I moved something from there into the css tutorial that should have been moved long ago).

I will work on a wiki update that adds the icon property to the widget page.

2025-01-05 06:41 UTC, 96LawDawg commented
The tutorial probably needs another look depending on when #2432 gets merged.

2025-07-09 22:51 UTC, 96LawDawg requested changes
Some icons are broken.  Maybe this changed since when we switched everything from Google Material Icons to Google Material Symbols?

![Screenshot 2025-07-09 174928](https://github.com/user-attachments/assets/c5cb655f-e42d-47c9-bd45-15d03078cfbb)

2025-07-11 15:52 UTC, merged