added applyVariables to Input fields
ArnoldSmith86/virtualtabletop pull request #214
Opened 2021-02-14 12:34 UTC by larkob

This PR adds applyVariables to any fields used in the INPUT operation.

2021-02-14 12:34 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3214/pr-test (or any other room on that server)

2021-02-14 12:39 UTC, larkob commented
I know the added code is pretty much a duplication, but I couldn't find a way to call a universal function because the `click` and `showInputOverlay` each are separate async functions with their own scope.

2021-02-14 12:52 UTC, UltimateGeek commented
@larkob , could you update the pr-test room with an example of using this change?

2021-02-14 12:55 UTC, larkob commented
Try to out the "Deal cards" button. It shows you your current playerName in the text input. You can then change it to some other name.

2021-02-14 13:05 UTC, larkob commented
One minor issue I noticed is that a value parameter (the one with "Guest922244") is automatically added. No idea why that is. If I remove the line and edit the button again, it is automatically added.
```
    {
      "func": "INPUT",
      "header": "suggests name based on playerName variable",
      "fields": [
        {
          "type": "string",
          "label": "Your name?",
          "variable": "myName",
          "applyVariables": [
            {
              "parameter": "value",
              "variable": "playerName"
            }
          ],
          "value": "Guest922244"
        }
      ]
    }
```

2021-02-14 16:00 UTC, robartsd commented
> One minor issue I noticed is that a value parameter (the one with "Guest922244") is automatically added. No idea why that is. If I remove the line and edit the button again, it is automatically added.
> 
> ```
>     {
>       "func": "INPUT",
>       "header": "suggests name based on playerName variable",
>       "fields": [
>         {
>           "type": "string",
>           "label": "Your name?",
>           "variable": "myName",
>           "applyVariables": [
>             {
>               "parameter": "value",
>               "variable": "playerName"
>             }
>           ],
>           "value": "Guest922244"
>         }
>       ]
>     }
> ```

This is what apply variables is doing. Variables in javascript don't actually contain objects of arrays, they contain a reference to the memory location where the object or array is stored. If you modify the object or array, all variables that reference that object or array will see the change; you don't get a completely different scope for the object or array unless you do a deep copy.

2021-02-14 17:48 UTC, pf-lkobbe commented
I don't really understand deep vs. shallow copies. When I started on this, it seemed like a simple thing, but apparently it's not and so I'm not sure how to proceed with this PR (as it is clearly beyond my coding skills).

2021-02-14 17:49 UTC, larkob commented
I don't really understand deep vs. shallow copies. When I started on this, it seemed like a simple thing, but apparently it's not and so I'm not sure how to proceed with this PR (as it is clearly beyond my coding skills).

2021-02-15 12:57 UTC, UltimateGeek commented on client/js/widgets/button.js
> +                problems.push('Entry in parameter applyVariables does not contain "parameter" together with "variable", "property", or "template".');
I don't think there is a problems array in this context.

2021-02-15 13:05 UTC, UltimateGeek commented on client/js/widgets/button.js
> +                problems.push('Entry in parameter applyVariables does not contain "parameter" together with "variable", "property", or "template".');
Take a look at my changes in #217 (which is pointed at this branch). I replicated the test in its pr-test room.

2021-02-15 13:22 UTC, rogerl50 commented
> > One minor issue I noticed is that a value parameter (the one with "Guest922244") is automatically added. No idea why that is. If I remove the line and edit the button again, it is automatically added.
> > ```
> >     {
> >       "func": "INPUT",
> >       "header": "suggests name based on playerName variable",
> >       "fields": [
> >         {
> >           "type": "string",
> >           "label": "Your name?",
> >           "variable": "myName",
> >           "applyVariables": [
> >             {
> >               "parameter": "value",
> >               "variable": "playerName"
> >             }
> >           ],
> >           "value": "Guest922244"
> >         }
> >       ]
> >     }
> > ```
> 
> This is what apply variables is doing. Variables in javascript don't actually contain objects or arrays, they contain a reference to the memory location where the object or array is stored. If you modify the object or array, all variables that reference that object or array will see the change; you don't get a completely different scope for the object or array unless you do a deep copy.
> 
> On line 69 `const a = { ...original }` performs a shallow copy of the routine function before proceeding. Keys of `a` that contain scalars have a copy of the scalar value that is not connected to the value in `original`; however, keys of `a` that contain objects contain the exact same object as `original` (not a copy). Thus applyVariables in the main function is not modifying `original` but applyVariables in the input fields is modifying `original`.
> 
> Perhaps line 69 should be changed to perform a deep copy instead of a shallow copy. Could also modify the applyVariables routine to work recursively so that the code is all in one place. If we did that, we'd need to decide if applyVariables works from the shallowest level to the deepest (more powerful as applyVariables could add an object that contains an applyVariables key; but could potentially cause an infinite loop) or from the deepest level to shallowest (safe, but less powerful).

That's really clear and interesting. Thanks. A question: would it be better to just do the deep copy once you are processing the `INPUT` tag? Doing it up top, in line 69, seems like a bit change. Are there any efficiency (or any other) concerns?

2021-02-18 10:50 UTC, ArnoldSmith86 requested changes
Looks fine. I agree with @UltimateGeek's comments.

- [ ] refactor `applyVariables`

2021-02-28 12:42 UTC, UltimateGeek approved these changes

2021-03-05 19:13 UTC, merged

2021-03-05 19:13 UTC, RaphaelAlvez approved these changes
tested and approved

2021-03-05 20:37 UTC, ArnoldSmith86 commented
Here are the save files of the PR server: [staging-PR-214.zip](https://github.com/ArnoldSmith86/virtualtabletop/files/6093246/staging-PR-214.zip)