Improvements to FLIP
ArnoldSmith86/virtualtabletop pull request #216
Opened 2021-02-14 19:11 UTC by larkob

Allows FLIP operation to override the faceCycle property of the items in the holder.

Introduces new faceCycle option `previous` (reverse direction).

Closes #62

2021-02-14 19:12 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3216/pr-test (or any other room on that server)

2021-02-14 20:45 UTC, 96LawDawg commented
This needs a little bit of tweaking.  It works fine for the card and the stick (from my Alleys game).  But it does not work well on the checker or the dice.  When it hits the last face, the room just flashes.  It needs to loop back around to the previous (highest) face.

2021-02-15 09:46 UTC, larkob commented
Thanks, I fixed the issue.

2021-02-15 13:20 UTC, 96LawDawg approved these changes
Approved through testing.  Did not review code.

2021-02-18 10:48 UTC, ArnoldSmith86 requested changes
I didn't test it but the code looks fine except for that one issue.

2021-02-18 10:48 UTC, ArnoldSmith86 commented on client/js/widgets/basicwidget.js
> +      const fC = (faceCycle == 'previous' || faceCycle == 'random') ? faceCycle : this.p('faceCycle');
- [ ] For `faceCycle == 'ordered'` this ignores the provided `faceCycle` and falls back to `this.p('faceCycle')` which could be something else.

2021-02-18 10:48 UTC, ArnoldSmith86 commented on client/js/widgets/basicwidget.js
> +        this.p('activeFace', (this.p('activeFace') == 0) ? this.p('faces').length-1 : this.p('activeFace') -1);
Just FYI: the parenthesis around `this.p('activeFace') == 0` are not necessary.

2021-03-05 19:14 UTC, RaphaelAlvez approved these changes
tested and approve

2021-03-10 11:19 UTC, larkob commented
@ArnoldSmith86 @96LawDawg I've made a few changes to the code because I wanted to add the collection parameter to FLIP while I'm at it, so please take another look if you have time.

2021-03-13 17:35 UTC, RaphaelAlvez commented
@larkob Tested and approved again. I downloaded the test room and I'm merging it as I said I would

2021-03-13 17:36 UTC, merged