added collection to MOVE and MOVEXY
ArnoldSmith86/virtualtabletop pull request #373
Opened 2021-04-09 19:34 UTC by larkob

This PR allows to use a collection as a source for MOVE and MOVEXY.

Note: Although you can define multiple `to` holders for MOVE, a collection will end up in the last holder. Technically, it first moves the collection to the first holder, then from the first to the next, and so on - so this is the correct (yet non-intuitive) behaviour.

At some later point we may want to allow distributing the collection across multiple holders, but that's beyond the scope of this PR because that functionality should have options for the desired distribution pattern.

2021-04-09 19:35 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3373/pr-test (or any other room on that server)

2021-04-10 23:35 UTC, 96LawDawg approved these changes
Approved through test.  I also tested several games that use MOVE and MOVEXY and they still worked fine also.

2021-04-20 20:32 UTC, larkob commented on client/js/widgets/widget.js
> +          source = c.parent.parent;
I've rewritten the code to clarify that this check tries to detect if widgets in the collection are already in the target holder.

2021-05-05 23:18 UTC, 96LawDawg requested changes
Doesn't work since the last time I checked.  In the test room, I tried a few things and it always just selected and moved one card.  The last thing I tried was a custom key ("movethiscard":true) and put it on 9 cards.  Debug shows the collection is correct, but only 1 card is moved.  Same problem with MOVEXY.

2021-06-04 20:06 UTC, bjalder26 commented
> Doesn't work since the last time I checked. In the test room, I tried a few things and it always just selected and moved one card. The last thing I tried was a custom key ("movethiscard":true) and put it on 9 cards. Debug shows the collection is correct, but only 1 card is moved. Same problem with MOVEXY.

I believe that was because it defaults to a count of 1.  I changed it to a high number, and it appears to work.  Likewise, lower numbers appear to work as well.

2021-06-04 21:06 UTC, bjalder26 commented
I noticed that when you select cards to `move` using a given property that if the count is limited it will not keep moving NEW cards into the holder, but instead will keep moving the same cards into the holder.  Maybe this is the desired behavior as the property can be removed or altered with `onEnter` (which is what I did) or through a `SET`.  However, I wanted to point it out in case you had something else in mind for how it was supposed to work.

2021-06-06 04:57 UTC, 96LawDawg approved these changes
Approved through test.  Interitus pointed out the issue I had was failing to use the `count` parameter.  With the clarification, this works as expected and can be merged.  Unfortunately, due to passage of time, it has gotten out of synch with the main branch and will require some hand's on tweaks.

2021-06-06 06:56 UTC, robartsd commented
Conflict in jsonedit.js is easy to resolve; conflict resolution is just picking up the removal of RANDOM adjacent to these changes.

Conflict in widget.js is more challenging. The last conflict here is simply that the new move helper functions are directly adjacent to a function that had async added. The other two conflicts involve the actual functions this changed having changes from main as well; most likely the new code needs `async` and `await` added appropriately (possibly also for the helper functions).

2021-06-23 06:26 UTC, bjalder26 commented
It looks like the first conflict here is that move and moveXY were are both updated in jsonedits.js AND that RANDOM was deleted in #488.  S it looks like we need to keep the move and moveXY from this PR, but delete RANDOM. https://github.com/ArnoldSmith86/virtualtabletop/pull/488/files
![image](https://user-images.githubusercontent.com/78324099/123046453-bdb77d80-d3c1-11eb-8382-a03683914f0a.png)

2021-06-23 07:32 UTC, bjalder26 commented
It looks like the 2nd conflict is centered around a change from `foreach` to `for of` and the addition of awaits and async. Those changes were made as part of #406.
![image](https://user-images.githubusercontent.com/78324099/123054410-71bd0680-d3ca-11eb-82aa-2f466a2d838a.png)

2021-06-24 14:46 UTC, rogerl50 requested changes
Please add a comment containing draft language to update the Wiki when this PR is merged, so we can keep the Wiki up to date.

2021-06-28 13:37 UTC, bjalder26 commented
> Please add a comment containing draft language to update the Wiki when this PR is merged, so we can keep the Wiki up to date.

I would think something like this:

## MOVE

This function moves widgets into a target holder.

Parameters:
* from: _holderID_ (or an array) - specifies the holder(s) that contains the widgets to move.
* collection: _collection name_ - specifies the collection of widgets to move.
* to: _holderID_ (or an array) - specifies the holder(s) that widgets should be moved into.  Since movement into only 1 holder is supported at this time, widgets will be moved into the last holder in an array.
* count: _number_ - limits the amount of moved widgets (defaults to 1 if omitted; use 0 to indicate no limit)

The parameter _face_ can optionally set the face of the moved widgets to the given value (see FLIP). If omitted, the widgets will be left as they are.

```JS
{
  "func": "MOVE",
  "from": "holderID",
  "to": "holderID",
  "count": 0
}
```
```JS
{
  "func": "MOVE",
  "collection": "myCollection",
  "to": "holderID",
  "count": 0
}
```

## MOVEXY

This function moves widgets to a specific position on the surface (i.e. outside any holders). In case the widgets are currently contained in another widget (e.g. pile or holder), they will be moved out before being moved to the given coordinates.

Parameters:
* from: _holderID_ (or an array) - specifies the holder that contains the widgets to move
* collection: _collection name_ - specifies the collection of widgets to move.
* count: _number_ - limits the amount of moved widgets (defaults to 1 if omitted; use 0 to indicate no limit)
* x: _number_ - the x position on the surface (defaults to 0)
* y: _number_ - the y position on the surface (defaults to 0)

The parameter _z_ can optionally set the z-order of the widget. If omitted, the z-order will be determined automatically.

The parameter _face_ can optionally set the face of the moved widgets to the given value (see FLIP). If omitted, the widgets will be left as they are.

Please note that the moved widgets can form _piles_ as if they were moved by players. They will NOT be placed into any _holders_ though, even if the coordinates match perfectly. Use _MOVE_ for that.

```JS
{
  "func": "MOVEXY",
  "from": "holderID",
  "count": 2,
  "face": 0,
  "x": 100,
  "y": 100,
  "z": 100
}
```
```JS
{
  "func": "MOVEXY",
  "collection": "myCollection",
  "count": 10,
  "face": 1,
  "x": 200,
  "y": 200,
  "z": 100
}
```

2021-06-28 13:39 UTC, bjalder26 approved these changes
Still seems to work after the conflicts were resolved.  Approved through testing.

2021-07-12 04:58 UTC, ArnoldSmith86 commented
Yeah. I'll just look at the code today and make another review.

2021-07-12 18:25 UTC, ArnoldSmith86 requested changes
I think it would be more consistent if a `count: 5` to multiple target holders would move 5 cards into each holder.

2021-07-12 18:25 UTC, ArnoldSmith86 commented on client/js/widgets/widget.js
> +          isInTargetHolder = (c.parent.parent == target);
You shouldn't use `c.parent` here. I'm pretty sure it's not what you want. It's not always the same as `widgets.get(c.get('parent'))` which is probably what you need here.

2021-08-20 20:47 UTC, bjalder26 commented
The 'conflict' here is from the addition of these lines in green.  The real conflict was already resolved.

![image](https://user-images.githubusercontent.com/78324099/130291551-a953951e-bf50-42de-87fa-5d1d50055aba.png)

2021-11-19 16:50 UTC, rogerl50 commented
This seems like a useful enhancement, and shouldn't require too much work to get it fixed and merged. There are conflicts that need to be dealt with (not only the trivial issue mentioned above, but a new one brought about by the introduction of anonymous collections), and a couple of comments above that need to be resolved.

2021-12-05 04:39 UTC, 96LawDawg commented
The only thing remaining from #60 are MOVE and MOVEXY.  All the other applicable functions have been modified to work with collections.  Seems like we should get this done for consistency.

2023-10-30 19:31 UTC, ArnoldSmith86 commented
Superseded by #1658 and #1888.

2023-10-30 19:31 UTC, closed without merging