variables playerName and playerColor are now writable
ArnoldSmith86/virtualtabletop pull request #560
Opened 2021-06-11 16:32 UTC by ArnoldSmith86

We discussed this in a meeting long, long ago.

Please note that this can only set the name and color of the player triggering the routine.

2021-06-11 16:32 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3560/pr-test (or any other room on that server)

2021-06-11 16:44 UTC, ArnoldSmith86 commented
Aaaand someone already managed to set `playerName` to `null`. :rofl:

2021-06-11 16:45 UTC, bjalder26 commented
> Aaaand someone already managed to set `playerName` to `null`. 🤣

Yeah, I wanted to make a random name generator, but I'm not done (it doesn't work yet), and now I have to run for a bit.

2021-06-11 16:49 UTC, robartsd requested changes

2021-06-11 16:49 UTC, robartsd commented on client/js/widgets/widget.js
> +    if(variables.playerColor != playerColor && typeof variables.playerColor == 'string')
Please check that the string matches  `/^#[0-9a-fA-F]{6}$/`.

2021-06-11 19:50 UTC, bjalder26 commented
I made a random name & color generator and noticed something odd.  Only one of them would update at a time.  It turned out that I was able to resolve that by putting the lines that set those variables together instead of having them separated by a bunch of computations. 

To be more specific, calculating a random color required a lot of computations, and the rando color would only update if the name did NOT update (was set to the same name).  Then when I moved the lines together to set those variables it worked.  Besides computations, there were a bunch of IF statements between them, so that might have been the issue too.

2021-06-11 20:00 UTC, ArnoldSmith86 commented
Always keep a copy of the buggy ones, please.

2021-06-11 20:04 UTC, bjalder26 commented
> Always keep a copy of the buggy ones, please.

I put it back in the room and limited it to two names so the chance of it 'bugging' is 50/50.

2021-06-12 22:56 UTC, bjalder26 commented
I did some more testing, and it is the IF separating the two variable changes that somehow prevents the two variables from changing at the same time.  Further, if the playerColor is the one before the `IF` statement, then it will never change, only the playerName will change.

I am guessing that the playerColor 'triggers' with the wrong playerName (or possibly no playerName) if it is separated from the playerName by an `IF` statement in the JSON.

2021-06-12 23:50 UTC, robartsd commented
> I did some more testing, and it is the IF separating the two variable changes that somehow prevents the two variables from changing at the same time. Further, if the playerColor is the one before the `IF` statement, then it will never change, only the playerName will change.
> 
> I am guessing that the playerColor 'triggers' with the wrong playerName (or possibly no playerName) if it is separated from the playerName by an `IF` statement in the JSON.
> 
> Of course, you can just not put an `IF` statement between them.

Sounds like the variables are getting written to state at the end of any (sub)routine not just the outermost routine. This causes issues when returning to the calling routine if the calling routine later interacts with the variables.

2021-06-13 00:08 UTC, robartsd commented
When we call the `thenRoutine` or `elseRoutine` all variables including the changed playerColor and playerName variables get passed to the routine. When the branch completes, the changes are queued up to be sent to the server rather than waiting to be queued up in the parent routine.

2021-06-13 04:25 UTC, ArnoldSmith86 commented
Yeah, I'm pretty sure I know how to fix it (locally also setting `playerName`). I just didn't have time yet.

2021-06-15 07:32 UTC, ArnoldSmith86 commented
Please check if the issues have been resolved.

2021-06-15 07:44 UTC, bjalder26 approved these changes
My intentionally buggy name generators now work fine.  I can't find any issues.  Approved based on testing.

2021-06-16 07:35 UTC, robartsd approved these changes

2021-06-16 12:24 UTC, ArnoldSmith86 commented
I was about to merge but I noticed a crash when player cursors are still updated with the old name or something like that. Gotta check..

2021-06-16 13:14 UTC, bjalder26 commented
> I was about to merge but I noticed a crash when player cursors are still updated with the old name or something like that. Gotta check..

Could it be when the player has gone inactive, then goes back and clicks a button to choose a new name?  I thought that might be the case, but I also assumed that was 'normal', since the page was probably 'stale' (with possible changes) and needed to be refreshed anyway.

2021-06-16 13:27 UTC, RaphaelAlvez commented
Can you add the tag to? It will need to be writable anyway so maybe that's a good opportunity to add it. And maybe also rename the color to remove "team" from there.
I got really confused when I was looking at that code

2021-06-16 14:19 UTC, ArnoldSmith86 commented
> I also assumed that was 'normal', since the page was probably 'stale' (with possible changes) and needed to be refreshed anyway.

If the complete page reloads, that means that the client had an unexpected error. It only reloads so that the players aren't left with a broken page. So ideally that should never happen.

> Can you add the tag to?

No, not now.

> And maybe also rename the color to remove "team" from there.
> I got really confused when I was looking at that code

Initially my idea was that the color is the team. So two red players would be the same team. I don't think that's a good idea anymore though.

2021-06-16 15:23 UTC, bjalder26 commented
> complete page reloads, that means that the client had an unexpected error. It only reloads so that the players aren't left with a broken page. So ideally that should never happen.

I think I may have found what causes it.  I opened the test room on my phone.  I can't see anything on my phone except what appears to be a blank screen.  If I scroll on my phone the page reloads on my laptop.

http://212.47.248.129:3560/pr-test

2021-06-16 15:26 UTC, robartsd commented
> Initially my idea was that the color is the team. So two red players would be the same team. I don't think that's a good idea anymore though.

I'd like to copy the idea of player number or initials in the cursor circle from PICO. If we did that then the cursor could represent the team with color and distinguish team members with the initials.

2021-06-19 11:29 UTC, merged

2021-06-21 03:45 UTC, 96LawDawg commented
I added a comment about how to set `playerName` and `playerColor` in the Functions section of the wiki.