added CODEOWNERS file
ArnoldSmith86/virtualtabletop pull request #57
Opened 2021-01-08 15:10 UTC by ArnoldSmith86

I enabled that pull requests require a review of the code owner before they can be merged. This file tells GitHub who owns what.

2021-01-08 15:11 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3057/pr-test (or any other room on that server)

2021-01-08 15:29 UTC, 96LawDawg submitted a review, later dismissed
This will be a little more work and will slow things down, but that is probably a good thing.

2021-01-09 17:43 UTC, UltimateGeek requested changes

2021-01-09 17:43 UTC, UltimateGeek commented on CODEOWNERS
> +/tests/ @UltimateGeek
```suggestion
jest.config.mjs @UltimateGeek
/tests/ @UltimateGeek
```

2021-01-10 22:49 UTC, UltimateGeek approved these changes
Thank you for establishing this. :-)

2021-01-14 03:13 UTC, 96LawDawg approved these changes
Looks good.  I approve.

2021-01-14 03:14 UTC, merged