New Game Pieces
ArnoldSmith86/virtualtabletop pull request #644
Opened 2021-07-06 04:33 UTC by RaphaelAlvez

Adds assets to game pieces and remove color options on add widget overlay

- [ ]  add a color picker to the add widget overlay
- [ ]  change UI to have a color picker whenever the image is an SVG (@robartsd and @ArnoldSmith86 I need help with this)
- [ ] adjust positions
- [ ] add dices
- [ ] add poker chips
- [ ] remove old game pieces?
- [ ] add option for text on editor UI (mostly for poker chips)

This PR requires documentation for svgReplace that I can refers to in the editor UI

2021-07-06 09:57 UTC, ArnoldSmith86 commented
Changing the default of `svgReplaces` won't be pretty BTW. For every basic widget in existence we need to add `svgReplaces` with the old defaults or look at the `image` first and only do it for SVGs.

2021-07-06 18:47 UTC, RaphaelAlvez commented
> Changing the default of `svgReplaces` won't be pretty BTW. For every basic widget in existence we need to add `svgReplaces` with the old defaults or look at the `image` first and only do it for SVGs.

Yeah you are right. This also would also make the UI easier.

2021-07-06 23:46 UTC, robartsd commented
You can always submit assets to add wtih color `#ff0000` intended for replacement. svgReplaces itself works with anything and someone else could change `#ff0000` to `currentColor` before it gets added to the official assets if desired.

2021-07-07 00:26 UTC, RaphaelAlvez commented
> You can always submit assets to add wtih color `#ff0000` intended for replacement. svgReplaces itself works with anything and someone else could change `#ff0000` to `currentColor` before it gets added to the official assets if desired. 

Yeah I'm

2021-07-07 00:53 UTC, RaphaelAlvez commented
> You can always submit assets to add wtih color `#ff0000` intended for replacement. svgReplaces itself works with anything and someone else could change `#ff0000` to `currentColor` before it gets added to the official assets if desired. 

Yeah I know. I feel this is the only path at the moment. I still want to keep the 

Just a bit sad because I think this setup I have now would be the ideal situation. Maybe we can consider this for the next update.

2021-07-08 08:02 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3644/pr-test (or any other room on that server)

2021-07-10 15:55 UTC, 96LawDawg commented
I'm not the best one to make a comment on this, but during dev-game-night play, this PR broke things.  Basic widget images would not load.

2021-07-10 15:57 UTC, ArnoldSmith86 commented
> I'm not the best one to make a comment on this, but during dev-game-night play, this PR broke things. Basic widget images would not load.

To be expected because of this todo:

>     * add file updater

2021-07-10 18:15 UTC, robartsd requested changes

2021-07-10 18:15 UTC, robartsd commented on client/js/widgets/basicwidget.js
> +      svgReplaces: {"#ff0000": "color"},
svgReplaces should be empty by default

2021-07-10 18:32 UTC, RaphaelAlvez commented
This PR was a draft for a reason. I might only be wrong in not adding the file updater tag.
If the SVG and color default were to be changed there would definitely be a file update.
I'm still pondering which of both options is the best. 
I think the file format I'm proposing is better but making the update may be ugly.

2021-07-10 18:51 UTC, robartsd commented
> This PR was a draft for a reason. I might only be wrong in not adding the file updater tag.
> If the SVG and color default were to be changed there would definitely be a file update.
> I'm still pondering which of both options is the best.
> I think the file format I'm proposing is better but making the update may be ugly.

Regardless of if you use `#ff0000` as the value that needs replacing in the SVG or use `currentColor` as existing assets do, svgReplaces should not have a replacement defined in the default set by basicwidget.js - the replacement should be set in the JSON for the widget using the asset. If you just add new assets, you don't need a file updater (even if the new assets use `#ff0000` as the color intended for replacement. A file updater would be required if you change the string being replaced in existing named assets.

2021-07-10 19:28 UTC, ArnoldSmith86 commented
@RaphaelAlvez I'm afraid we can't implement your idea of a default `svgReplaces`. It did sound cool that `color` would "just work" but the problem is that `svgReplaces` has a high cost and limitations:

There's no easy way to know if the asset URL in the `image` property is actually an SVG. The problem on the staging server was that it was downloading PNGs and applying `svgReplaces` to it. While the code could be changed to first detect if it is an SVG, I don't think it is worth it for this change. We would basically have to reimplement the browser's downloading, caching and handling of images and it would happen for every basic widget everywhere.

There are probably quite a few shortcuts that would make it easier than that but my gut tells me it's not worth it.

Maybe an alternative would be a new widget type for game pieces that only accepts SVGs? Or instead of `image` it would have `svg` and `png`?

And BTW, the default could also replace _both_ `"currentColor"` _and_ `"#ff0000"` by `color`.

2021-07-10 19:35 UTC, robartsd commented
I do think that it would make sense for the JSON editor to make it extremely easy to add the code needed to replace "currentColor" and/or "#ff0000" with the value of the color property.

2021-10-30 17:43 UTC, closed without merging