SET = instead of + if value is null
ArnoldSmith86/virtualtabletop pull request #728
Opened 2021-08-14 01:33 UTC by bjalder26

This addresses issue #727

It would make it so the JSON below would give you "property1": "new text" instead of "property1": "nullnew text" if the property was a null value previously.
{
"func": "SET",
"property": "property1",
"relation": "+",
"value": "new text",
"collection": "thisButton"
}

**May require a file version bump**

2021-08-14 01:33 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3728/pr-test (or any other room on that server)

2021-09-22 18:42 UTC, rogerl50 commented
Why is this specific to `+`? How about the other relations? Are there any cases where we wouldn't want to simply convert to `=`?

2021-09-22 22:04 UTC, bjalder26 commented
> Why is this specific to `+`? How about the other relations? Are there any cases where we wouldn't want to simply convert to `=`?

The reason why with + is because it was concatenating new values with `null`.  So if there happened to be no value, and you use `+` to add 'this text' not being able to know beforehand that it would be null, then you would get 'nullthis text'.  In other words, because as far as concatenating text goes, when no value is shown it actually has a "hidden" text value of "null".

My thought was that if a game designer added (`+`) text to what appears to be nothing (null), they would expect to just get the same value back, and certainly not the value appended to `null`.

I can't think of another relation that would work that way, but I could be missing something.

2021-09-23 12:07 UTC, rogerl50 commented
> I can't think of another relation that would work that way, but I could be missing something.

Fair enough; I tested other relations and they work in a reasonable way.

How about the (admittedly unlikely) case where the property being modified has a value, but the value being added is null? At present, this produces `'oldvaluenull'`. Here, just setting the relation to `=` probably gives unexpected results; perhaps setting the second value to `''` is the best option? I'm not sure. Or perhaps we should just leave it alone.

2021-09-23 12:19 UTC, bjalder26 commented
> > I can't think of another relation that would work that way, but I could be missing something.
> 
> Fair enough; I tested other relations and they work in a reasonable way.
> 
> How about the (admittedly unlikely) case where the property being modified has a value, but the value being added is null? At present, this produces `'oldvaluenull'`. Here, just setting the relation to `=` probably gives unexpected results; perhaps setting the second value to `''` is the best option? I'm not sure. Or perhaps we should just leave it alone.

Good catch.  I'm thinking that in that case there should not be a SET at all.  I think that would give the expected result in all cases.

2021-09-23 14:09 UTC, rogerl50 requested changes

2021-09-23 14:09 UTC, rogerl50 commented on client/js/widgets/widget.js
> +             if(!(a.relation == '+' && a.value == null))
1) Indentation is off on the newly added if (and the subsequent statement).
2) It is probably worthwhile to add something like
```
            problems.push(`null value being appended, SET ignored`)
```

2021-09-23 15:07 UTC, rogerl50 commented
BTW this is still marked Draft...

2021-09-23 15:12 UTC, bjalder26 commented
> BTW this is still marked Draft...

I made it draft again when I realized I should make the change you pointed out.  Now I somehow lost my test room :).

2021-10-01 02:24 UTC, merged