Informational overlay revamps
ArnoldSmith86/virtualtabletop pull request #980
Opened 2021-12-07 01:26 UTC by mousewax

Revamps to both the About page and the Connection Lost page to just add a little polish.

2021-12-07 01:26 UTC, ArnoldSmith86 commented
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3980/pr-test (or any other room on that server)

2021-12-07 02:42 UTC, bjalder26 commented
Maybe this table could use some padding.
![image](https://user-images.githubusercontent.com/78324099/144956294-7720f6e4-3719-4427-ac54-01485aa7f52c.png)

2021-12-07 02:48 UTC, mousewax commented
That table took me by surprise. It's not on my local copy.

2021-12-07 03:03 UTC, bjalder26 commented
> That table took me by surprise. It's not on my local copy. And I have no idea why it's on this screen.

It's part of the new beta servers update.

2021-12-07 03:27 UTC, mousewax commented
![image](https://user-images.githubusercontent.com/12822213/144960855-d856fa7a-be12-4de0-8710-b77b0e7d54f1.png)

How is this?

2021-12-07 03:39 UTC, bjalder26 commented
In my opinion it all looks really nice.

2021-12-07 16:30 UTC, 96LawDawg commented
I agree.  Looks really nice.  What is the source of the plug graphic?  Is attribution required?

2021-12-07 16:36 UTC, mousewax commented
Attribution is not required. It's new work made by me from stock images that I own.

2021-12-07 16:50 UTC, RaphaelAlvez requested changes

2021-12-07 16:50 UTC, RaphaelAlvez commented on client/css/overlays/about.css
> +  margin:;
: ;

2021-12-07 16:53 UTC, 96LawDawg commented
> Attribution is not required. It's new work made by me from stock images that I own.

@ArnoldSmith86, how do you want to handle that?  Most of the attribution notes are in the variants.  But this wouldn't fit there.  Put it on the attribution page with the comment about the deck?

2021-12-07 18:30 UTC, RaphaelAlvez commented
> @ArnoldSmith86, how do you want to handle that? Most of the attribution notes are in the variants. But this wouldn't fit there. Put it on the attribution page with the comment about the deck?

I think this is pretty straightforward. @mousewax should add an attribution paragraph for all the assets they created if that's what they want.
My assets were never on that page because I didn't feel the need for it

2021-12-07 18:39 UTC, 96LawDawg commented
It isn't about protecting mousewax.  It is about protecting VTT.  Listing the source of all graphics or other potentially copyrighted material helps prevent issues down the road.

2021-12-07 18:56 UTC, robartsd commented
> It isn't about protecting mousewax. It is about protecting VTT. Listing the source of all graphics or other potentially copyrighted material helps prevent issues down the road.

If his license for the stock images allow him to create from them without restrictions, can't he put his work into the public domain?

2021-12-07 19:07 UTC, 96LawDawg commented
Yes.  And he says he wants to maximize his stuff in the public domain.  So we just need to say it is a VTT asset and is in the public domain.  But my point is we need to say that somewhere so nobody looks at that and asks where did that cool cable come from?

2021-12-07 19:21 UTC, robartsd commented
On the about overlay we have:

### Copyright Attribution
The default card deck was created by Adrian Kennard and released under CC0 Public Domain license: https://www.me.uk/cards/.

Perhaps it should be:
### Copyright Attribution
All images served under https://virtualtabletop.io/i/ are available from the GitHub repository under an open source license.

2021-12-07 22:24 UTC, ArnoldSmith86 commented
The connection lost overlay flashes for me quickly when I (re)load the page. Is it just me or does this only happen with this PR?

2021-12-07 22:27 UTC, robartsd commented
> The connection lost overlay flashes for me quickly when I (re)load the page. Is it just me or does this only happen with this PR?

I think I've seen that in production occasionally as well.

2021-12-08 02:24 UTC, mousewax commented
Would having a paragraph somewhere saying: 

All graphics used on this site were either created by members of the VTT development team or sourced from works in the public domain. Great care has been made to attribute the sources where appropriate. If you feel your work has been appropriated or used without your consent, please wrote to LawDawg because he's the one that said we could use it.

(The last sentence is of course humor, but something along these lines.)

2021-12-08 02:30 UTC, RaphaelAlvez commented
> Would having a paragraph somewhere saying: 
> 
> All graphics used on this site were either created by members of the VTT development team or sourced from works in the public domain. Great care has been made to attribute the sources where appropriate. If you feel your work has been taken or used without your consent, please write to LawDawg because he's the one that said we could use it.
> 
> (The last sentence is of course humor, but something along these lines.)

No no. That is totally correct. We should keep it

2021-12-08 02:32 UTC, 96LawDawg commented
LawDawg left the chat.  JohnSmith96 joined the chat.

2021-12-08 02:40 UTC, robartsd commented
> All graphics used on this site were either created by members of the VTT development team or sourced from works in the public domain.

This is not a true statement. It is not even true for https://virtualtabletop.io/i/ (some assets there are CC BY). Public library contains assets that are CC BY NC. Anyone can upload files and have them served under https://virtualtabletio.io/assets/

2021-12-08 03:12 UTC, mousewax commented
> All graphics used on this site were either created by members of the VTT development team or sourced from works in the public domain or made available for public use through Creative Commons or other similar licenses. Great care has been made to attribute the sources where appropriate. If you feel your work has been taken or used without your consent, please contacts....

2021-12-08 14:36 UTC, RaphaelAlvez commented
> > All graphics used on this site were either created by members of the VTT development team or sourced from works in the public domain or made available for public use through Creative Commons or other similar licenses. Great care has been made to attribute the sources where appropriate. If you feel your work has been taken or used without your consent, please contact us and immediate action will be taken to remove any infringing works.

I like this. @96LawDawg and @robartsd how do you feel about it?

2021-12-08 14:41 UTC, robartsd commented
> > > All graphics used on this site were either created by members of the VTT development team or sourced from works in the public domain or made available for public use through Creative Commons or other similar licenses. Great care has been made to attribute the sources where appropriate. If you feel your work has been taken or used without your consent, please contact us and immediate action will be taken to remove any infringing works.
> 
> I like this. @96LawDawg and @robartsd how do you feel about it?

Would like some language indicating where they can find the assets with associated licenses so that we meet any "share alike" clauses of licenses of the assets that we use.

2021-12-09 02:45 UTC, 96LawDawg commented
We need a way to distinguish things "in the code" and things "in the library."  For stuff in the library, the current copyright attribution language works I think.

For stuff in the code, something like: "All graphics used on this site were either created by members of the VTT community and are released into the public domain or sourced from works in the public domain or made available for public use through Creative Commons or other similar licenses."  Stuff in the code includes the cable that started this discussion and VTT-Symbols.  I'm not aware of anything else.

Then an overall statement that says "Great care has been made to attribute the sources where appropriate. If you feel your work has been taken or used without your consent, please contact us and immediate action will be taken to remove any infringing works."

I'm not worried about random things that show up in /assets/ with checksum names and that are only linked to games that aren't in the public library.

2021-12-10 07:15 UTC, mousewax commented
Tell me what words to put in which places and I will make it happen.

2021-12-14 18:11 UTC, ArnoldSmith86 approved these changes
I don't see problems in the changed code. I'm not 100% sure if the template tags work in every browser we support.

I really like the polish on the about overlay.

2021-12-14 19:02 UTC, 96LawDawg approved these changes
Approve with the comments noted above.

2021-12-15 00:03 UTC, merged